### ISSUE TITLE
Multi Args Support (args sequence)

### ISSUE THREAD

**Issue by ThayalanGR** [actions-hub/kubectl#1]
![image](https://user-images.githubusercontent.com/35830033/80271619-6e9f8b00-86df-11ea-84ed-52c628c9c1eb.png)

**Comment by seonglae** [comment]
any update?

**Comment by ThayalanGR** [comment]
> any update?

Not sure, but this could help https://github.com/openbeats/openbeats/blob/master/.github/workflows/clientapp.yml

**Comment by exelban** [comment]
Hi. Sorry for such a long response.
There is no way to do it. Because of [github action support](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepswith) only string in the `with` section. And there could not be multiple params. 

So it's not possible to do it. The best way to achieve that is to have a few steps with different commands.
